name: Validate with HACS

on:
  pull_request:
  push:
    branches:
      - main
      - master

jobs:
  hacs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: HACS Action
        uses: hacs/action@main
        with:
          category: 'integration'
